version: '3.8'

services:
  api-trasformer:
    container_name: api-trasformer
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: 'redis:alpine'
